### ISSUE TITLE
Catalina support

### ISSUE THREAD

**Issue by n0brainer** [Shufflepuck/SplashBuddy#121]
Any plans to bring Catalina support? 1.3.3 seems like it should work as long as the dialog popups are constantly cleared.  Unfortunately they pop under SB and it's not easy to get at them.

**Comment by Ethenyl** [comment]
Hi @n0brainer,

Thanks for creating a ticket. I'll be looking into the issue you're facing asap.

Regarding the upgrade to Catalina (10.15) SB should support it without any changes. From the issue description, I'll need more information in order to determine what exactly is the issue.

Which popup are your referring to? The missing `jamf.log` one?

And which version of the Catalina BETA are you using?

**Comment by n0brainer** [comment]
Yeah, going through again on the latest beta, it appears to be TCC with terminal and wanting to access the network volumes and stuff.
<img width="532" alt="Screen Shot 2019-08-06 at 7 42 50 AM" src="https://user-images.githubusercontent.com/2116991/62559759-2aaee200-b841-11e9-90bd-a24f48dbd32d.png">
<img width="488" alt="Screen Shot 2019-08-06 at 7 43 08 AM" src="https://user-images.githubusercontent.com/2116991/62559769-30a4c300-b841-11e9-96a1-5dd2ef4713cc.png">
<img width="488" alt="Screen Shot 2019-08-06 at 7 49 36 AM" src="https://user-images.githubusercontent.com/2116991/62559775-35697700-b841-11e9-86b5-96908f85a277.png">

**Comment by canalnoises** [comment]
@n0brainer Are you able to use PPPC configuration profiles to suppress these dialogs?

**Comment by n0brainer** [comment]
that's my next step, we can close this out for now.
